/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * OpenAPI demo
 * OpenAPI spec version: 1.0
 */

export type GetPostsParams = {
/**
 * Number of posts to return
 */
first?: unknown;
/**
 * Cursor for pagination
 */
after?: string;
};
