/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * OpenAPI demo
 * OpenAPI spec version: 1.0
 */

export * from './createPostDto';
export * from './getPostsParams';
export * from './pageInfoDto';
export * from './postDto';
export * from './postEdgeDto';
export * from './postsConnectionDto';
export * from './updatePostBody';