/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * OpenAPI demo
 * Simple APIs for managing posts
 * OpenAPI spec version: 1.0.0
 */

export * from './badRequestResponse';
export * from './getPostsParams';
export * from './notFoundResponse';
export * from './pageInfo';
export * from './patchPostsIdBody';
export * from './post';
export * from './postEdge';
export * from './postPostsBody';
export * from './postsConnection';