/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * OpenAPI demo
 * OpenAPI spec version: 1.0
 */

export interface PageInfoDto {
  /** Whether there are more pages available */
  hasNextPage: boolean;
  /** The cursor of the last item in the current page */
  endCursor: string;
}
