/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * OpenAPI demo
 * OpenAPI spec version: 1.0
 */
import type { PostEdgeDto } from './postEdgeDto';
import type { PageInfoDto } from './pageInfoDto';

export interface PostsConnectionDto {
  /** Array of post edges */
  edges: PostEdgeDto[];
  /** Information about pagination */
  pageInfo: PageInfoDto;
}
