/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * OpenAPI demo
 * OpenAPI spec version: 1.0
 */

export interface PostDto {
  /** The unique identifier for the post */
  id: number;
  /** The title of the post */
  title: string;
  /** The body of the post */
  body: string;
}
