/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * OpenAPI demo
 * Simple APIs for managing posts
 * OpenAPI spec version: 1.0.0
 */
import type { Post } from './post';

export interface PostEdge {
  node: Post;
  cursor: string;
}
