/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * OpenAPI demo
 * Simple APIs for managing posts
 * OpenAPI spec version: 1.0.0
 */

export type PostPostsBody = {
  title: string;
  body: string;
};
