/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * OpenAPI demo
 * Simple APIs for managing posts
 * OpenAPI spec version: 1.0.0
 */

export interface Post {
  /** The unique identifier for the post */
  id: number;
  /** The title of the post */
  title: string;
  /** The body of the post */
  body: string;
}
