/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * OpenAPI demo
 * OpenAPI spec version: 1.0
 */
import type { PostDto } from './postDto';

export interface PostEdgeDto {
  /** The post node */
  node: PostDto;
  /** The cursor for pagination */
  cursor: string;
}
